baseURL = 'https://blog.suyuri.com'
languageCode = 'zh-cn'
title = "Suyurine's Blog"
theme = "hugo-PaperMod"

[params]
    env = "production"
    # å¼€å¯ä¸ªäººä¸»é¡µæ¨¡å¼
    [params.homeInfoParams]
        Title = "ä½ å¥½ï¼Œæˆ‘æ˜¯ Suyurine ğŸ‘‹"
        Content = "æ¬¢è¿æ¥åˆ°æˆ‘çš„æŠ€æœ¯å°å±‹ï¼Œè¿™é‡Œè®°å½•æˆ‘çš„æŠ˜è…¾æ—¥å¸¸ã€‚"

    # ç¤¾äº¤é“¾æ¥
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/ä½ çš„ç”¨æˆ·å"

    # æ˜¾ç¤ºâ€œæ–‡ç« ç›®å½•â€
    [params.ShowToc]
        TocOpen = true

# é…ç½®å¯¼èˆªæ 
[[menu.main]]
    identifier = "posts"
    name = "æ–‡ç« "
    url = "/posts/"
    weight = 10
[[menu.main]]
    identifier = "archives"
    name = "å½’æ¡£"
    url = "/archives/"
    weight = 20